cd C:\Users\admin\Desktop\gobha-shop\run
call parent.bat
cd C:\Users\admin\Desktop\gobha-shop\run
call common.bat
cd C:\Users\admin\Desktop\gobha-shop\run
call mapper.bat
cd C:\Users\admin\Desktop\gobha-shop\run
call model.bat
cd C:\Users\admin\Desktop\gobha-shop\run
call service.bat
cd C:\Users\admin\Desktop\gobha-shop\run
call web.bat
echo Success
cd C:\Users\admin\Desktop\gobha-shop